type size = 'Pequeno' | 'Médio' | 'Grande';

type dogData = {
  id: number;
  breed: string;
  image: string;
  size: size;
  countryOrigin: string;
  colors: string[];
  lifeExpectancy: string;
  adultWeightKg: string;
  classification: string[];
};

const data: dogData[] = [
  {
    id: 1,
    breed: 'Labrador Retriever',
    image: 'labrador_retriever.png',
    size: 'Médio',
    countryOrigin: 'Canadá',
    colors: ['Preto', 'Chocolate', 'Amarelo'],
    lifeExpectancy: '10 a 12 anos',
    adultWeightKg: '25 a 36 kg',
    classification: ['Companhia', 'Assistência'],
  },
  {
    id: 2,
    breed: 'Golden Retriever',
    image: 'golden_retriever.png',
    size: 'Médio',
    countryOrigin: 'Escócia',
    colors: ['Dourado claro', 'Dourado médio', 'Dourado escuro'],
    lifeExpectancy: '10 a 12 anos',
    adultWeightKg: '25 a 34 kg',
    classification: ['Companhia', 'Assistência'],
  },
  {
    id: 3,
    breed: 'Poodle',
    image: 'poodle.png',
    size: 'Pequeno',
    countryOrigin: 'Alemanha/França',
    colors: ['Branco', 'Preto', 'Marrom', 'Cinza', 'Dourado', 'Apricot'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '6 a 12 kg',
    classification: ['Companhia', 'Competições de agilidade'],
  },
  {
    id: 4,
    breed: 'Bulldog Francês',
    image: 'bulldog_frances.png',
    size: 'Pequeno',
    countryOrigin: 'França',
    colors: ['Fulvo', 'Tigrado', 'Preto', 'Branco', 'Cinza'],
    lifeExpectancy: '10 a 12 anos',
    adultWeightKg: '8 a 14 kg',
    classification: ['Companhia'],
  },
  {
    id: 5,
    breed: 'Bulldog Inglês',
    image: 'bulldog_ingles.png',
    size: 'Médio',
    countryOrigin: 'Reino Unido',
    colors: ['Branco', 'Caramelo', 'Tigrado', 'Vermelho'],
    lifeExpectancy: '8 a 10 anos',
    adultWeightKg: '18 a 25 kg',
    classification: ['Companhia'],
  },
  {
    id: 6,
    breed: 'Pastor Alemão',
    image: 'pastor_alemao.png',
    size: 'Grande',
    countryOrigin: 'Alemanha',
    colors: ['Preto e marrom', 'Cinza', 'Preto sólido'],
    lifeExpectancy: '9 a 13 anos',
    adultWeightKg: '22 a 40 kg',
    classification: ['Guarda', 'Resgate', 'Companhia'],
  },
  {
    id: 7,
    breed: 'Beagle',
    image: 'beagle.png',
    size: 'Médio',
    countryOrigin: 'Reino Unido',
    colors: ['Marrom', 'Branco', 'Preto', 'Tricolor'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '9 a 14 kg',
    classification: ['Caça', 'Companhia'],
  },
  {
    id: 8,
    breed: 'Rottweiler',
    image: 'rottweiler.png',
    size: 'Grande',
    countryOrigin: 'Alemanha',
    colors: ['Preto com marrom'],
    lifeExpectancy: '8 a 10 anos',
    adultWeightKg: '35 a 60 kg',
    classification: ['Guarda', 'Companhia'],
  },
  {
    id: 9,
    breed: 'Yorkshire Terrier',
    image: 'yorkshire_terrier.png',
    size: 'Pequeno',
    countryOrigin: 'Reino Unido',
    colors: ['Cinza', 'Dourado', 'Preto'],
    lifeExpectancy: '13 a 16 anos',
    adultWeightKg: '2 a 3 kg',
    classification: ['Companhia'],
  },
  {
    id: 10,
    breed: 'Shih Tzu',
    image: 'shih_tzu.png',
    size: 'Pequeno',
    countryOrigin: 'China',
    colors: ['Branco', 'Marrom', 'Preto', 'Dourado', 'Cinza'],
    lifeExpectancy: '10 a 16 anos',
    adultWeightKg: '4 a 7 kg',
    classification: ['Companhia'],
  },
  {
    id: 11,
    breed: 'Border Collie',
    image: 'border_collie.png',
    size: 'Médio',
    countryOrigin: 'Reino Unido',
    colors: ['Preto e branco', 'Merle', 'Tricolor', 'Marrom e branco'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '14 a 20 kg',
    classification: ['Assistência', 'Companhia'],
  },
  {
    id: 12,
    breed: 'Dachshund',
    image: 'dachshund.png',
    size: 'Pequeno',
    countryOrigin: 'Alemanha',
    colors: ['Marrom', 'Preto com marrom', 'Vermelho', 'Tigrado'],
    lifeExpectancy: '12 a 16 anos',
    adultWeightKg: '7 a 14 kg',
    classification: ['Caça', 'Companhia'],
  },
  {
    id: 13,
    breed: 'Boxer',
    image: 'boxer.png',
    size: 'Grande',
    countryOrigin: 'Alemanha',
    colors: ['Caramelo', 'Tigrado', 'Branco'],
    lifeExpectancy: '10 a 12 anos',
    adultWeightKg: '25 a 32 kg',
    classification: ['Guarda', 'Companhia'],
  },
  {
    id: 14,
    breed: 'Doberman',
    image: 'doberman.png',
    size: 'Grande',
    countryOrigin: 'Alemanha',
    colors: ['Preto com marrom', 'Marrom', 'Azul', 'Isabela'],
    lifeExpectancy: '10 a 13 anos',
    adultWeightKg: '30 a 45 kg',
    classification: ['Guarda', 'Companhia'],
  },
  {
    id: 15,
    breed: 'Husky Siberiano',
    image: 'husky_siberiano.png',
    size: 'Grande',
    countryOrigin: 'Rússia',
    colors: ['Cinza', 'Preto e branco', 'Vermelho', 'Branco puro'],
    lifeExpectancy: '12 a 14 anos',
    adultWeightKg: '20 a 27 kg',
    classification: ['Companhia', 'Competições de agilidade'],
  },
  {
    id: 16,
    breed: 'Chihuahua',
    image: 'chihuahua.png',
    size: 'Pequeno',
    countryOrigin: 'México',
    colors: ['Marrom', 'Preto', 'Branco', 'Dourado', 'Mesclado'],
    lifeExpectancy: '14 a 17 anos',
    adultWeightKg: '1,5 a 3 kg',
    classification: ['Companhia'],
  },
  {
    id: 17,
    breed: 'Pug',
    image: 'pug.png',
    size: 'Pequeno',
    countryOrigin: 'China',
    colors: ['Bege', 'Preto', 'Prata', 'Abricot'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '6 a 9 kg',
    classification: ['Companhia'],
  },
  {
    id: 18,
    breed: 'Vira-lata',
    image: 'vira_lata.png',
    size: 'Médio',
    countryOrigin: 'Brasil',
    colors: ['Preto', 'Caramelo', 'Branco', 'Mesclado'],
    lifeExpectancy: '12 a 16 anos',
    adultWeightKg: '10 a 25 kg',
    classification: ['Companhia', 'Guarda'],
  },
  {
    id: 19,
    breed: 'Cocker Spaniel',
    image: 'cocker_spaniel.png',
    size: 'Médio',
    countryOrigin: 'Reino Unido',
    colors: ['Dourado', 'Preto', 'Chocolate', 'Tricolor', 'Azul ruão'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '12 a 15 kg',
    classification: ['Caça', 'Companhia'],
  },
  {
    id: 20,
    breed: 'Maltês',
    image: 'maltes.png',
    size: 'Pequeno',
    countryOrigin: 'Itália',
    colors: ['Branco puro'],
    lifeExpectancy: '12 a 15 anos',
    adultWeightKg: '3 a 4 kg',
    classification: ['Companhia'],
  },
  {
    id: 21,
    breed: 'Fila Brasileiro',
    image: 'fila_brasileiro.png',
    size: 'Grande',
    countryOrigin: 'Brasil',
    colors: ['Caramelo'],
    lifeExpectancy: '9 a 11 anos',
    adultWeightKg: '40 a 60 kg',
    classification: ['Guarda', 'Caça'],
  },
  {
    id: 22,
    breed: 'Fox Paulistinha',
    image: 'fox_paulistinha.png',
    size: 'Médio',
    countryOrigin: 'Brasil',
    colors: ['Tricolor'],
    lifeExpectancy: '13 a 16 anos',
    adultWeightKg: '6 a 10 kg',
    classification: ['Companhia', 'Competições de agilidade'],
  },
];

export const getDogs = {
  getAll: (): dogData[] => {
    return data;
  },
  getFromBreed: (breed: string): dogData[] => {
    return data.filter(i => i.breed.toLowerCase().indexOf(breed.toLowerCase()) > -1)
  },
  getFromSize: (size: size): dogData[] => {
    return data.filter(i => i.size === size);
  },
  getFromColors: (colors: string): dogData[] => {
    return data.filter(i => i.colors.includes(colors));
  },
  getFromCountry: (country: string): dogData[] => {
    return data.filter(i => i.countryOrigin === country)
  },
  getFromId: (id: number): dogData => {
    return data.find(i => i.id === id)!;
  }
}